response_codes={
    "SUCCESS":"PA00",
    'INTERNAL_ERROR':'PA01',
    'REQUEST_ERROR':'PA02',
    'ALREADY_EXIST':'PA03',
    'ADD_SUCCESS':'PA04',
    'SIGNUP_ERROR':'PA05',
    'NOT_FOUND':'PA06',
    'USER_DELETED' : 'PA07',
    'ERROR_DELETION': 'PA08',
    'DOES NOT EXIST':'PA09',
    'SUCCESSFULLY FETCHED':'PA09'
}

MAIL_SERVER = 'smtp.office365.com'
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USERNAME = 'support@mystratify.com'
MAIL_PASSWORD = 'GdHRW5zWHTB2IIIsA85ixJhhmCaI4'